create table Citizens (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  zip CHAR(4) NOT NULL,
  age BIGINT NOT NULL,
  email VARCHAR(200) NOT NULL,
  taj CHAR(9) NOT NULL,
  number_of_vaccination TINYINT UNSIGNED DEFAULT 0,
  last_vaccination DATETIME)